# QuickHarvest Configuration
# Version: 1.0.0

require-sneaking: false
creative-mode: false

messages:
  no-permission: "&cYou don't have permission to use QuickHarvest!"

crops:
  WHEAT: true
  CARROTS: true
  POTATOES: true
  BEETROOT: true
  NETHER_WART: true