name: QuickHarvest
version: 1.0.0
main: com.quickharvest.QuickHarvest
api-version: 1.20
authors: Gamingop
description: Auto-harvest and replant crops with right-click
commands:
  quickharvest:
    description: Reload the plugin configuration
    permission: quickharvest.reload
    usage: /quickharvest reload

permissions:
  quickharvest.use:
    description: Allows using QuickHarvest features
    default: true
  quickharvest.reload:
    description: Allows reloading the plugin
    default: op